import react, { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
export default function Home() {
  const [data, setData] = useState(null)

  useEffect(() => {
    document.title = 'First Next App'
    axios
      .get('https://pl-test-api.herokuapp.com/api/v1/data')
      .then((response) => {
        if (response.data) {
          setData(response.data)
        } else {
          setData(null)
        }
      })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container p-10 text-center'>
        <h1 className='mb-10 text-slate-800 font-semibold text-3xl'>
          Welcome to My First Next.js App!
        </h1>
        <p className='text-xl font-light text-black'>
          This app simple retrive data from online api based on heroku made my
          me
        </p>
        <p className='mt-5 text-xl font-light text-black'>
          you can discover the api from
          <a
            className=' text-blue-500 hover:text-blue-800 hover:underline'
            href='https://pl-test-api.herokuapp.com/'
          >
            Here
          </a>
        </p>

        <div className=' container mt-10'>
          {data ? (
            data.map((item) => (
              <div
                key={item.id}
                className='w-auto justify-center items-center bg-white shadow-lg rounded-lg flex flex-col mb-5'
              >
                <div className='w-full h-auto object-cover rounded-t-lg'>
                  <Image
                    src={`https://pl-test-api.herokuapp.com${item.thumbnail}`}
                    alt={item.name + ' logo'}
                    height={200}
                    width={400}
                  />
                </div>
                <div className='w-full p-4 justify-start flex flex-col'>
                  <h4 className='text-2xl text-black'>{item.name}</h4>
                  <p className='my-4 text-gray-900'>{item.description}</p>
                  <hr className='border-b border-bookmark-white' />
                  <p className='text-gray-500 mt-5'>
                    relased At: {item.released_year} - Github Rank:
                    {item.githut_rank}
                  </p>

                  <a
                    href={item.link}
                    target='_blank'
                    rel='noreferrer'
                    type='button'
                    className='rounded-full my-4 px-4 py-2 text-white hover:bg-blue-700 bg-blue-500'
                  >
                    Read more
                  </a>
                </div>
              </div>
            ))
          ) : (
            <p>Loading...</p>
          )}
        </div>
      </main>

      <footer className=' container mt-4 text-center py-5 border-t'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
